[project]
name = "sorrydb"
version = "0.1.0"
description = "Build a continously updating database of sorry statments in public Lean4 repositories"
authors = [{ name = "Your Name", email = "you@example.com" }]
license = { text = "Apache License" }
readme = "README.md"
requires-python = ">=3.13"


[tool.poetry.dependencies]
gitpython = "*"
requests = "^2.32.3"
pydantic = "^2.10.6"


[tool.poetry.group.dev.dependencies]
pytest = "^8.3.4"

[tool.poetry]
packages = [
	{ include = "sorrydb/scripts", from = "src" },
	{ include = "sorrydb/crawler", from = "src" },
	{ include = "sorrydb/repro", from = "src" },
	{ include = "sorrydb/database", from = "src" },
]


[tool.poetry.scripts]
find_sorries = "sorrydb.scripts.find_sorries:main"
get_lean_repos = "sorrydb.scripts.get_lean_repos:main"
get_mathlib_contributors = "sorrydb.scripts.get_mathlib_contributors:main"
offline_sorries = "sorrydb.scripts.offline_sorries:main"
build_sorry_db = "sorrydb.scripts.build_sorry_db:main"


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
